spring.application.name: TaskManager


server:
  port: 8080

spring:
  main:
    allow-circular-references: true   # ??????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskmanger?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.taskmanager.pojo.Entity # ?????
  mapper-locations: "classpath*:/mapper/**/*.xml" # Mapper.xml????????
  configuration:
    map-underscore-to-camel-case: false # ?????????????
    cache-enabled: false # ????????
  global-config:
    db-config:
      update-strategy: not_null # ????????????





# knife4j????
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    com:
      taskmanager:
        mapper: debug
        service: info
        controller: info
